### ISSUE TITLE
veritical workspaces toggle

### ISSUE THREAD

**Issue by allaeddineomc** [G-dH/vertical-workspaces#34]
the extension offers a great amount of customization that can be very useful with the default horizontal workspaces , i think it will be a great addition to have the option to disable vertical workspaces while staying able to make use of the other features like changing the position of workspace previews , hiding the workspace bg and using the gradually blurred static background and the neat animations that are much better than the default IMO .

**Comment by G-dH** [comment]
Horizontal update available, you can help me with testing if you want ;)

**Comment by allaeddineomc** [comment]
sorry for not replying , the notification was lost in my messy inbox 
i will try it

**Comment by allaeddineomc** [comment]
it's working amazingly aside form the app grid animation not working and the 3 finger up/down gestures not working , the gestures can be easily fixed by enabling gesture improvements extension

**Comment by G-dH** [comment]
Thanks for the feedback. The app grid animation should work, now also from the top. Can you elaborate the problem with more detail? Swipe tracker orientation should be fixed now, I don't use system with trackpad (will test it later), but the swipe animation should be ok, I can simulate it on my mouse and I'm watching every frame.

**Comment by allaeddineomc** [comment]
now swiping from right to left is entering the overview and there is no gesture for changing the workspace , the app grid animation is still not there 

https://user-images.githubusercontent.com/57415185/211026001-342be26f-a94b-4b1d-9ef6-9ff144f7984b.mp4

**Comment by G-dH** [comment]
Enable the animation on `Behavior` tab.

**Comment by G-dH** [comment]
Trackpad works, tested on Fedora 36. Update your installation from the repository, if you didn't do that.

**Comment by allaeddineomc** [comment]
i have reset the extension and tested it again and now everything works aside from the 3 finger up/down gestures (on horizontal overview ), i think a good fix will be to add a toggle to disable gesture overrides , also when switching horizontal workspaces the OSD is still vertical 
![Screenshot from 2023-01-06 15-17-22](https://user-images.githubusercontent.com/57415185/211029883-f9174847-aef0-4857-b0d4-15c4138d25e4.png)

**Comment by G-dH** [comment]
Have you installed the latest version from the repo? I'm working on it, you can see related commits here.

**Comment by G-dH** [comment]
Disable all other extensions and let me know if it helps. In the horizontal mode the swipe module stays untouched by VW, so if it works in default GNOME, it also should work with VW.

**Comment by G-dH** [comment]
By disabling other extensions I mean disable them and restart shell.

**Comment by allaeddineomc** [comment]
i will try that in a new user account just to make sure everything is default

**Comment by allaeddineomc** [comment]
didn't fix the problem

**Comment by allaeddineomc** [comment]
works perfectly after the latest commit

**Comment by allaeddineomc** [comment]
tested it more with and without all the extensions i have installed and it seems to be ready to release , it crashes the desktop when used with searchlight extension but i don't think that the issue have anything to do with any of the projects , thanks for you amazing work , this extension is a piece of art .

**Comment by G-dH** [comment]
Thanks, some details still need to be polished. I'm very focused on details in animations, transitions and usability and it's harder with any new feature (that's the reason GNOME devs keep it simple as possible :). Have you noticed any differences in performance and responsiveness of the UI compared to the original Shell?

The _Search Light_ used to work OK when I tested it some time ago, it's still in my system, but you're right, now it's unusable. And without relevant log...

**Comment by allaeddineomc** [comment]
for me , the performance seems better with the extension enabled because i use it with animations slowed a little bit so everything feels smoother in general , speaking of details , there is a small detail that i wanted to talk about but i guess it deserves a separate issue , it's about when the static background is enabled and the workspace preview background is disabled , i guess it will be much nicer to have the background not move when switching workspaces (when not in overview) in this case 
while i was writing this i noticed a weird behavior when using the type to search when the app grid is shown

**Comment by allaeddineomc** [comment]
i have a theory on why searchlight breaks when 'vertical workspaces' is enabled , i guess it have to do with 'vertical workspaces' effecting the styling of the search view

**Comment by G-dH** [comment]
I noticed the app grid under the search results, it should be fixed already.
> i guess it will be much nicer to have the background not move when switching workspaces (when not in overview)

I'll try to add the option.

When it comes to the Search Light conflict, VW only adjusts background/font colors of the search view, that is something that cannot conflict with anything. In any case, it's not my priority now.

**Comment by G-dH** [comment]
> i guess it will be much nicer to have the background not move when switching workspaces (when not in overview) 

Added `Workspace Switcher Animation` on `Behavior` tab.

**Comment by allaeddineomc** [comment]
tested it and it works great , the only issue with it is when dynamic workspaces are disabled the user can have more than 1 empty workspace and there will be no way to tell if it's scrolling or not , to workaround this you can show the workspace switching OSD while preforming the gestures

**Comment by G-dH** [comment]
Yeah, I realized that too. The switch indicator was my first idea, but then I got another one... I'll do something with it.

**Comment by G-dH** [comment]
So I added the default popup indicator, it should be consistent and it also works with the popup replacement when using my WSM extension.
